Make registry publishing release step easier to debug (#229)
- Add before and after log statements for the two login commands. This helps isolate when one of them fails versus previously this is the output:

```
+ set +x
Error: Cannot perform an interactive login from a non TTY device
```

- Change curl `-s` to `-sS` so that errors are output on failure
- Add `-e` to `jq` so that parse failures error out and stop the propagation to the next pipe

Co-authored-by: Ed Morley <501702+edmorley@users.noreply.github.com>

GUS-W-11917558.