Add libc6-dev into the stack image (#179)
Currently on heroku-18 and heroku-20 you cannot compile at runtime, but can on heroku-16. This prevents `mjit` which relies on out of band compilation to implement jit. Here are some details about how I uncovered this:

On a heroku run bash instance this code fails on heroku-18 but works on heroku-16:

```
~ $ cat > numprocessors.c <<EOL
>   #include <unistd.h>
>   #include <stdio.h>
>
>   int main() {
>     int val = sysconf(_SC_NPROCESSORS_ONLN);
>     printf("# => Number of processors from sysconf: %i\n", val);
>     return 0;
>   }
> EOL
~ $ gcc numprocessors.c && ./a.out
numprocessors.c:1:12: fatal error: unistd.h: No such file or directory
   #include <unistd.h>
            ^~~~~~~~~~
```

here's a blog post from when it worked https://schneems.com/2017/08/01/is-webrick-webscale/

Also Ruby's "mjit" does not work on Heroku-18:

```
~ $ ruby --jit-wait --jit-verbose=5 -e "puts 'yoyoyoyo'"
MJIT: CC defaults to /usr/bin/gcc
MJIT: tmp_dir is /tmp
Locking in mjit_cont_new
Locked in mjit_cont_new
Click to expand inline (14 lines)
```

It deadlocks since it's never able to compile anything using mjit, it prints those unlock/lock lines out forever.